PREFIX fam:  <http://www.ifi.uio.no/IN3060/family#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sim:  <http://www.ifi.uio.no/IN3060/simpsons#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

CONSTRUCT {
  sim:Homer a foaf:Person .
  sim:Homer foaf:knows ?b .
  sim:Homer foaf:name "Homer Simpson" .
  ?b a foaf:Person .
  ?b foaf:name "Marge Simpson" .
} 

WHERE {
	sim:Homer fam:hasSpouse ?b .
}

